### PR TITLE
Added support for FriendlyName to xCertReq - Fixes #44

### LINKED ISSUE #44: xCertReq friendly name?
Would be nice to be able to specify this. I want to create the cert, but later I want to use the name in another task or script. Nothing to key off of otherwise.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR primarily adds support for specifying the Friendly Name of new certificates created using xCertReq. 

It also makes style and other changes for consistency and HQRM compatibility.

- xCertReq:
  - Added FriendlyName parameter to xCertReq.
  - Changed exceptions to be raised using New-InvalidOperationException from PSDscResources.
  - Changed integration tests to use Config Data instead of value in config to support
    additional tests.
  - Converted unit tests to use Get-InvalidOperationRecord in CommonTestHelper.
  - Improved unit test style to match standard layout.
  - Minor corrections to style to be HQRM compliant.
- Corrected all makrdown rule violations in README.MD.
- Added markdownlint.json file to enable line length rule checking in VSCode
  with [MarkdownLint extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
  installed.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/69)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @johlju or @bgelens - if either of you have any downtime (I know you don't :grin:) would you mind looking over this PR for me? No rush at all- I just don't have anyone else maintaining this repo so have no official reviewers to check my code.

This is a smallish change but I did fix some existing style issues.

**Comment by johlju** [comment]
@PlagueHO I trade with you ;) Can you see if you have a good idea for my problem here https://github.com/PowerShell/xSQLServer/issues/641 while I review your PR tomorrow :smile:

**Comment by PlagueHO** [comment]
@johlju - it's a deal :grin:

I've looked into this now though and haven't managed to get much more than a bad work around. Looks like we've got the same problem in a couple of resources as well. Maybe the DSC Team can offer some suggestions?

**Comment by johlju** [comment]
:lgtm:

Nice cleanup in the tests :)

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/69#-:-KmwDLY5VGYtibL9OxUB:bn46nxm)*

**Comment by PlagueHO** [comment]
Awesome! Thanks @johlju - and yep - I've been trying to clean everything up with each PR.

**Pull request merged**
