### PR TITLE
Added functionality to xPfxImport and fixed issue #17

### LINKED ISSUE #17: Invalid Thumbprint error
I was unable to use the xPfxImport to import a certificate. It was giving me an error message that my hash was invalid. I used the same hash and certificate with the import-pfxcertificate cmdlet and it worked fine. If there is any more information that I can supply, let me know, I'd like to avoid using the script resources for this if I can.

### PR DESCRIPTION
**Pull request by DdenBraver**
This pull request contains the following updates:

- Added support for CurrentUser as location
- Added Ensure parameter, to remove certificates where needed
- Added Provider$ as filter in Validate-Thumbprint to resolve #17
- Added a ValidationSet to the $Store parameter
- Changed xPfxImport Keys to make them more Unique
- Test script MSFT_xPfxImport.tests updated

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/19)

### CODE REVIEW

**Comment by briantist** [comment]
@DdenBraver hi, please remove `[ValidateSet()]` for the store. I left it out specifically because you can't determine the set at design time; it's possible to add new stores. As an example, the WebHosting store does not exist until you install IIS.

A Dynamic Parameter could handle this, but since it's a DSC resource that would be useless.

**Comment by DdenBraver** [comment]
@briantist Thanks for the feedback, I was indeed facing the same issue where I did want to validate the input against something.

What I could do is validate the $certpath exists.
I could place this in the Get-TargetResource (which gets called by Test-TargetResource) to throw an exception if its not available.

**Comment by DdenBraver** [comment]
@KarolKaczmarek @briantist @TravisEz13 
Please let me know how you think about my last comment, so I can change the code accordingly.

**Comment by TravisEz13** [comment]
@DdenBraver  I agree that you cannot have a static validation of the stores.  Your proposal seems reasonable, but this assumes the resource is not supposed to create the store.  This also seems reasonable.

**Comment by TravisEz13** [comment]
Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEO2DDLc5QlZ7T2jfTw:1110108576) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
We need to at least note the breaking change and what the  user needs to change to work with this breaking change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by DdenBraver** [comment]
*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEawmKtHtVlIVf8kl1H:-1108270239) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
I do not think this should be a breaking change, as the default value of the Ensure parameter is Present.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEcAGQRG5pYbzIf6Fv_:-196040214) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
'Store' went from optional to being a key.  This is a breaking change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by DdenBraver** [comment]
*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEceeapW4gM3rr3AVmO:-1886124834) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
I just updated the readme.md showing this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by TravisEz13** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEiIVqz_nDNVRxL0Uaq:-357987904) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
@KarolKaczmarek Is there any special way we want to indicate a change is breaking?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by iainbrighton** [comment]
Surely it would need to have a major version bump on the next release cycle? And some big/bold in the readme.md!

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEmPfXy4ael5XM7xy_T:592242418) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
@ddenbraver  I followed up with Karol offline, can you change `* Updated xPfxImport Store parameter is now a key value making it mandatory·' to `* Breaking Change - Updated xPfxImport Store parameter is now a key value making it mandatory·'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by DdenBraver** [comment]
*[ReadMe.md, line 46 \[r3\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEO2DDLc5QlZ7T2jfTv:-KEmVWAjE_FOnzl7VPR6:-1635501379) ([raw file](https://github.com/powershell/xcertificate/blob/060cb6d3b4426a9a1c929397b36597875c8ba01e/ReadMe.md#L46)):*
Changed as requested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ReadMe.md, line 46 \[r5\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEmc64hTrxKu4RUJkh5:-KEmc64hTrxKu4RUJkh6:-1080658198) ([raw file](https://github.com/powershell/xcertificate/blob/8d69a13a57ded82123d5e84b55e9791b801438de/ReadMe.md#L46)):*
unicode character in readme

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 46 \[r5\]](https://reviewable.io:443/reviews/powershell/xcertificate/19#-KEmc64hTrxKu4RUJkh5:-KEmd40OaZJ5FJKycg7l:-1858541117) ([raw file](https://github.com/powershell/xcertificate/blob/8d69a13a57ded82123d5e84b55e9791b801438de/ReadMe.md#L46)):*
This is not blocking, consider fixing or filing an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19)*

**Comment by TravisEz13** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/19#-:-KEmdGctnLyKubvCta9O:1417088721)*

**Pull request merged**
