### PR TITLE
New PR, replacing PR43

### PR DESCRIPTION
**Pull request by svenvanrijen**
Changed all lines as discussed under PR 43 and issue 42.

Regarding error when requesting cerificate using $credential and error regarding single quotes around the $ca variable value (issue #42)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/52)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thanks @svenvanrijen - great job and appreciate all the work. Just one minor tweak to the readme and I'll merge. Thanks again.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 80 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/52#-Kfp4eFiCzMt9zOEyACZ:-Kfp4eFiCzMt9zOEyAC_:bfsea6v) ([raw file](https://github.com/powershell/xcertificate/blob/f431ee5944cd813953dfe08258001861befa7055/ReadMe.md#L80)):*
> ```Markdown
> 
> - xCertReq:
>     - Fixing issue #42 (Error when requesting cerificate using $credential and error regarding single quotes around the $ca variable value):
> ```

Fantastic job there - but slightly overkill for release notes :grin: The DSC Resource Kit team use these notes to notify users on the MSFT PowerShell blog of what is changed - so this is a bit much detail and doesn't really mention what the fix does :grin:

Could you just change this to something like:
```
- Fixed issue where xCertReq does not process requested certificate when credentials parameter set and PSDscRunAsCredential not passed. See [issue](https://github.com/PowerShell/xCertificate/issues/49)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/52#-:-Kfp66FPMol1W70bcTNk:b-lwjb3x)*

**Comment by svenvanrijen** [comment]
hi @PlagueHO . No problem!
Just changed readme.md and uploaded again.

Cheers, Sven

**Comment by svenvanrijen** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 80 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/52#-Kfp4eFiCzMt9zOEyACZ:-KfqP8_9lQ4BF56VtR5c:bcnzwkj) ([raw file](https://github.com/powershell/xcertificate/blob/f431ee5944cd813953dfe08258001861befa7055/ReadMe.md#L80)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Fantastic job there - but slightly overkill for release notes :grin: The DSC Resource Kit team use these notes to notify users on the MSFT PowerShell blog of what is changed - so this is a bit much detail and doesn't really mention what the fix does :grin:

Could you just change this to something like:
```
- Fixed issue where xCertReq does not process requested certificate when credentials parameter set and PSDscRunAsCredential not passed. See [issue](https://github.com/PowerShell/xCertificate/issues/49)
```
</blockquote></details>

Changes made as proposed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/52)*

**Comment by PlagueHO** [comment]
:lgtm: Thanks for all your work on this! Really appreciate it! :grin: merging now.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/52#-:-Kg17KeC5JxQAePDsxAk:b-kmr45k)*

**Pull request merged**
