### PR TITLE
CA auto-discovery (fixes #27)

### LINKED ISSUE #27: [New Feature] xCertificate - Make CAServerFQDN and CARootName optional
User story: we have different CA's for different AD forests. Each CA in each AD domain has a different name. We want to use the same DSC configuration scripts across all domains.

To do this means that the CA details should be able to be automatically detected if not provided. This can be done by using certutil.exe -dump:
untitled

Are there any objections to this being implemented?

### PR DESCRIPTION
**Pull request by nyanhp**
This pull request contains the following changes:
- xCertReq:
  - Added CA auto-discovery to resource xCertReq.
  - Added SAN and certificate template name to xCertReq's Get-TargetResource
  - Added new parameter UseMachineContext to be able to use CA templates that try to fill the subject alternative name like e.g. DomainControllerAuthentication
- CertificateDSc.Common:
  - Added function Get-CertificateTemplateName to retrieve template name
  - Added function Get-CertificateSan to retrieve subject alternative name
  - Added function Find-CertificateAuthority to enable auto-discovery

I could not come up with any meaningful unit tests for the new functions since all of them are using call to .NET classes.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/53)

### CODE REVIEW

**Comment by nyanhp** [comment]
CLA signed three times already...

**Comment by PlagueHO** [comment]
Hi @nyanhp, Wow! Epic! Great job. I've just merged another PR to this repo which has caused some conflicts with yours. Can you please resolve and I'll review - again, awesome stuff. Thank you!

**Comment by nyanhp** [comment]
Hi @PlagueHO , all done! Thanks for reviewing yet another of my PRs :)

**Comment by PlagueHO** [comment]
Hi @nyanhp - Sorry I've taken so long. I'll review this in the weekend.

**Comment by PlagueHO** [comment]
@nyanhp - the Microsoft bot thinks you need to sign the CLA. I'll close and open this PR to see if that fixes it.

**Comment by PlagueHO** [comment]
@nyanhp - it looks like you'll still need to sign the CLA (or at least the MSFT bot thinks you need to).

**Comment by PlagueHO** [comment]
Really great job @nyanhp - top stuff! Only a couple of minor style changes and nitpicks. Will need to work out the CLA issue though before this can be merged.

---

Reviewed 3 of 7 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 637 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWOSieentrjxbLCa2b:-KhWOSieentrjxbLCa2c:bdv2xvl) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L637)):*
> ```PowerShell
>     {
>         $cert = Get-Childitem -Path Cert:\LocalMachine\My |
>         Where-Object -FilterScript {
> ```

Nitpick: Could you please indent this line (and the following 3) so that it is more obvious that is a continuation of the previous line (e.g. pipeline)

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 341 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWPWJYT6UxMcs0w_nn:-KhWPWJYT6UxMcs0w_no:b-y8qc6d) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L341)):*
> ```PowerShell
>         if (-not $DomainName)
>         {
>             $configContext = ([ADSI]"LDAP://RootDSE").configurationNamingContext
> ```

Nitpick: Use single quotes

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 345 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWQUgtHlNvVKA6ZO40:-KhWQUgtHlNvVKA6ZO41:b-mt3if2) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L345)):*
> ```PowerShell
>         else
>         {
>             $ctx = New-Object System.DirectoryServices.ActiveDirectory.DirectoryContext('Domain', $DomainName)
> ```

Can you use named parameter here (e.g. -TypeName)

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 350 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWPOFpkKTcBm4JQUse:-KhWPOFpkKTcBm4JQUsf:brpd0b0) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L350)):*
> ```PowerShell
> 
>         Write-Verbose -Message ($LocalizedData.ConfigurationNamingContext `
>         -f $configContext)
> ```

Could you please indent this line?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 351 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWP_sOux0BpVtm811O:-KhWP_sOux0BpVtm811P:b-y8qc6d) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L351)):*
> ```PowerShell
>         Write-Verbose -Message ($LocalizedData.ConfigurationNamingContext `
>         -f $configContext)
>         $cdpContainer = [ADSI]"LDAP://CN=CDP,CN=Public Key Services,CN=Services,$configContext"
> ```

Nitpick: Use single quotes

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 355 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWPldB1DxfSAncpehq:-KhWPldB1DxfSAncpehr:b-j96obb) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L355)):*
> ```PowerShell
>     catch
>     {
>         Write-Error -Message ($LocalizedData.DomainContactError -f $DomainName) -TargetObject $DomainName
> ```

This essentially obfuscates the underlying error. It would be a good idea to output the error message/details as well to make problem identification easier.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 372 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWQjXB2iQWmFUia2tl:-KhWQjXB2iQWmFUia2tm:b-mt3if2) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L372)):*
> ```PowerShell
>             }
>                         
>             $locatorInfo = New-Object System.Diagnostics.ProcessStartInfo
> ```

Can you use named parameter here (e.g. -TypeName)

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 382 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWQlo3aE_ZzwmMptU2:-KhWQlo3aE_ZzwmMptU3:b-mt3if2) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L382)):*
> ```PowerShell
>             $locatorInfo.CreateNoWindow = $true
> 
>             $locatorProcess = New-Object System.Diagnostics.Process
> ```

Can you use named parameter here (e.g. -TypeName)

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 401 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWR5zeyuBKttjDdO4Y:-KhWR5zeyuBKttjDdO4Z:b-1024z0) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L401)):*
> ```PowerShell
>     {
>         Write-Verbose -Message ($LocalizedData.CaFoundMessage -f $certificateAuthority.CAServerFQDN, $certificateAuthority.CARootName)
>         $certificateAuthority
> ```

Nitpick: can you change to ```return $certificateAuthority``` - this makes it a little more obvious that this is the return value.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 439 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWRbGwOM4eXmntGER8:-KhWRbGwOM4eXmntGER9:bd6c5ba) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L439)):*
> ```PowerShell
>         $temp = $Certificate.Extensions | Where-Object {$PSItem.Oid.Value -eq "1.3.6.1.4.1.311.21.7"}
>         $null = $temp.Format(0) -match 'Template=(?<TemplateName>.*)\('
>         $TemplateName = $Matches.TemplateName -replace ' '
> ```

Please use lower case first letter for local variables.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 447 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWRZzyDI7480sRHyfR:-KhWRZzyDI7480sRHyfS:b-qee5f7) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L447)):*
> ```PowerShell
>     }
> 
>     $TemplateName
> ```

Nitpick: can you change to ```return $templateName``` - this makes it a little more obvious that this is the return value.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 470 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWSA0_i0Du6A7CCOpF:-KhWSA0_i0Du6A7CCOpG:b-a6vne) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L470)):*
> ```PowerShell
>     )
> 
>     if ($Certificate.GetType().Name -ne 'System.Security.Cryptography.X509Certificates.X509Certificate2')
> ```

You could use:
```powershell
$Certificate - isnot [System.Security.Cryptography.X509Certificates.X509Certificate2]
```

---

*[Modules/CertificateDsc.Common/en-us/CertificateDsc.Common.strings.psd1, line 6 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWSjt91fsIQcfOZajt:-KhWSjtAjB6EShmpFUUG:beuc1bw) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/en-us/CertificateDsc.Common.strings.psd1#L6)):*
> ```PowerShell
>     CertificatePathError                = Certificate Path '{0}' is not valid.
>     SearchingForCertificateUsingFilters = Looking for certificate in Store '{0}' using filter '{1}'.
>     ConfigurationNamingContext          = "Using the following container to look for CA candidates: 'LDAP://CN=CDP,CN=Public Key Services,CN=Services,{0}'"
> ```

Could you remove extra double quotes around string?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53#-:-KhWSu6v6-fphiBNr2xS:buaiwrx)*

**Comment by nyanhp** [comment]
Hi @PlagueHO , thanks for the valuable input. I always tend to forget about -is and -isnot, eventhough I use similar things in C#.

**Comment by PlagueHO** [comment]
@nyanhp - I'm with you there - I forget it too :grin:

**Comment by PlagueHO** [comment]
Hi @nyanhp - I'll finish this review this weekend. But in the mean time, any chance you could fix the merge conflicts (caused because xCertificate was released today to the Resource Kit)?

**Comment by nyanhp** [comment]
Hi @PlagueHO, thanks for all the work you are doing. I fixed the merge conflicts (and added the new parameter to the comment-based help which I forgot...)

**Comment by PlagueHO** [comment]
Always happy to review and thanks for all the work - this will be a great addition! Just one tiny thing left (the type comparison) and I'll merge.

---

Reviewed 2 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 470 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWSA0_i0Du6A7CCOpF:-KiJTmxFQtd9tJoBIq1i:bv59o2m) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L470)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

You could use:
```powershell
$Certificate - isnot [System.Security.Cryptography.X509Certificates.X509Certificate2]
```

</blockquote></details>

Did you mean to change this type check as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53#-:-KiJU4mE_1ioaR04hyrd:b-m0i49h)*

**Comment by nyanhp** [comment]
Hi @PlagueHO , I forgot to change this comparison... I only went through the positive type comparisons, and somehow ignored the negated one. It's done now.

**Comment by PlagueHO** [comment]
Hi @nyanhp - I'm trying to get through all these PR's - sorry it's taking so long. Are you able to resolve the merge conflicts for me and I'll get the review done. Again, sorry about the delays!

**Comment by nyanhp** [comment]
Conflicts successfully resolved :)

**Comment by nyanhp** [comment]
Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 470 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KhWSA0_i0Du6A7CCOpF:-KjbNFLoQNOvkwGonK5l:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/450c70a1ebdb532e3947ced9b0c23c8357872695/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L470)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Did you mean to change this type check as well?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53)*

**Comment by PlagueHO** [comment]
Great work @nyanhp ! Thank you for all the work you're doing on these resources - really awesome stuff!

Are you able to add some unit tests for the new functions in CertificateDsc.Common? We're going to be adding some automatic code coverage reports to this repo soon so we'll be wanting to make sure we hit 80%.

---

Reviewed 4 of 4 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[ReadMe.md, line 83 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgH27KjHS63IkCNqH7:-KjgH27Li_sejmUWTbPN:bvan8i6) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/ReadMe.md#L83)):*
> ```Markdown
> ### Unreleased
> - Added mandatory properties for xPfxImport resource example.
> ```

Are you able to remove this blank line? The PS Team has some automation that generates the release notes and it may get tripped up by this blank line (I'm not certain though - just want to make sure).

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 126 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgLBhLu4V8lFz50jiV:-KjgLBhLu4V8lFz50jiW:b-16u1ut) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L126)):*
> ```PowerShell
>         $AutoRenew,
> 
>         [Parameter()]
> ```

Minor nitpick: Could you move this parameter down to the end so it matches the Set-*/Test-* and the Comment based help order (sorry - I know this is so minor - but I'm OCD :grin: )

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 321 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgLvAbv-vK1z9gC2L6:-KjgLvAcvj5hvEbDbogS:b-4plimt) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L321)):*
> ```PowerShell
> .SYNOPSIS
>     Automatically locate a certificate authority in Active Directory
> .DESCRIPTION
> ```

Just for consistency, could you separate each section with a line feed?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 411 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMljc6Nz6sIpHeZeZ:-KjgMljc6Nz6sIpHeZe_:b-4plimt) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L411)):*
> ```PowerShell
> .SYNOPSIS
>     Get a certificate template name
> .DESCRIPTION
> ```

Just for consistency, could you separate each section with a line feed?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 423 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMq5YByBCjTtD2pjJ:-KjgMq5YByBCjTtD2pjK:b-ehuahg) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L423)):*
> ```PowerShell
>     (
>         # The certificate for which a template is needed
>         [Parameter(Mandatory)]
> ```

Can you change to [Parameter(Mandatory = $true)] ?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 428 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMy8IMAvs0mItkMpX:-KjgMy8IMAvs0mItkMpY:bjepll7) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L428)):*
> ```PowerShell
>     )
> 
>     if($Certificate -isnot [System.Security.Cryptography.X509Certificates.X509Certificate2])
> ```

Please add space after if

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 436 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgN113vfmRWHE2t-Tb:-KjgN113vfmRWHE2t-Tc:b-77a5gs) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L436)):*
> ```PowerShell
>     if ("1.3.6.1.4.1.311.21.7" -in $Certificate.Extensions.oid.Value)
>     {
>         $temp = $Certificate.Extensions | Where-Object {$PSItem.Oid.Value -eq "1.3.6.1.4.1.311.21.7"}
> ```

Can you put spaces between the { and } to improve readability?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 452 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMn1H2oc7HQLYrEZO:-KjgMn1ILDkw2JYC2iYO:b-4plimt) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L452)):*
> ```PowerShell
> .SYNOPSIS
>     Get certificate SAN
> .DESCRIPTION
> ```

Just for consistency, could you separate each section with a line feed?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 464 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgNQFcnZ6uOH1-4Q3Q:-KjgNQFcnZ6uOH1-4Q3R:b-ehuahg) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L464)):*
> ```PowerShell
>     (
>         # The certificate for which the subject alternative names are needed
>         [Parameter(Mandatory)]
> ```

Can you change to [Parameter(Mandatory = $true)] ?

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 476 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgN_45JCI2EJFHfxpx:-KjgN_45JCI2EJFHfxpy:b-77a5gs) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L476)):*
> ```PowerShell
>     $subjectAlternativeName = [string]::Empty
>     
>     $sanExtension = $Certificate.Extensions | Where-Object {$_.Oid.FriendlyName -match "subject alternative name"}
> ```

Can you put spaces between the { and } to improve readability?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53#-:-KjgNi9Q1MhUO4edJmh3:bd08fcr)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 478 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgOdU0lpsF816vlO7X:-KjgOdU0lpsF816vlO7Y:b-ld88z) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L478)):*
> ```PowerShell
>     $sanExtension = $Certificate.Extensions | Where-Object {$_.Oid.FriendlyName -match "subject alternative name"}
>     
>     if($null -eq $sanExtension)
> ```

Can you add a space after the if ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53)*

**Comment by nyanhp** [comment]
Will do. I think I can work around the .NET calling by introducing a new function and mocking that but that will still leave 30% of Find-CertificateAuthority uncovered in tests - but to be honest: I don't see a way around that. I am open to suggestions :) As for the other two functions: I will probably be able to add unit tests for them by constructing a X509Certificate2 object.

**Comment by nyanhp** [comment]
Review status: 6 of 8 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[ReadMe.md, line 83 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgH27KjHS63IkCNqH7:-KjiIxyVc1izirhShKQd:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/ReadMe.md#L83)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Are you able to remove this blank line? The PS Team has some automation that generates the release notes and it may get tripped up by this blank line (I'm not certain though - just want to make sure).
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 126 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgLBhLu4V8lFz50jiV:-KjiJLzacqjy1OXzbj6F:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L126)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Minor nitpick: Could you move this parameter down to the end so it matches the Set-*/Test-* and the Comment based help order (sorry - I know this is so minor - but I'm OCD :grin: )
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 321 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgLvAbv-vK1z9gC2L6:-KjiJXV3KmK2CZAR_2oU:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L321)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Just for consistency, could you separate each section with a line feed?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 411 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMljc6Nz6sIpHeZeZ:-KjiK1dYSaKdKmY1rJGS:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L411)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Just for consistency, could you separate each section with a line feed?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 423 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMq5YByBCjTtD2pjJ:-KjiK4Cbpw9IWw00u6f2:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L423)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to [Parameter(Mandatory = $true)] ?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 428 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMy8IMAvs0mItkMpX:-KjiKbGOvg6KEJvZo_n9:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L428)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Please add space after if
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 436 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgN113vfmRWHE2t-Tb:-KjiKu6U4tjrnLgO3vA2:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L436)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you put spaces between the { and } to improve readability?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 452 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgMn1H2oc7HQLYrEZO:-KjiL5wDuxMWf-UytL_O:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L452)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Just for consistency, could you separate each section with a line feed?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 464 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgNQFcnZ6uOH1-4Q3Q:-KjiL8kTqauCdze-tFdn:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L464)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to [Parameter(Mandatory = $true)] ?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 476 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgN_45JCI2EJFHfxpx:-KjiLFE3Ik03RDHUJS4s:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L476)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you put spaces between the { and } to improve readability?
</blockquote></details>

Done.

---

*[Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, line 478 at r8](https://reviewable.io:443/reviews/powershell/xcertificate/53#-KjgOdU0lpsF816vlO7X:-KjiLGOMHLjKV6A6Fh3B:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/1c5e9310a0c3ec0a48c5335d6a516e9eaa0c73d3/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1#L478)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a space after the if ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53)*

**Comment by nyanhp** [comment]
I went through the open comments on reviewable. I still need to implement enough tests to reach full coverage for xCertReq itself, where I only mocked the new functions. Expect this to happen sometime during this week, until then: No action required :)

**Comment by nyanhp** [comment]
Hi @PlagueHO , I am done. I hope test coverage is good enough. If not, please let me know!

**Comment by PlagueHO** [comment]
Thanks @nyanhp ! You rock! Really appreciate this. I'll review tomorrow night - sorry for the delay.

**Comment by PlagueHO** [comment]
Amazing job @nyanhp - love the way you did the testing.

:lgtm: 

---

Reviewed 1 of 4 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/53#-:-KkPUUpfq8u6iN-vkyes:bgdrumt)*

**Pull request merged**
