### PR TITLE
Adding xPfxImport DSC Resource

### PR DESCRIPTION
**Pull request by briantist**
Adds the `xPfxImport` resource, see https://github.com/PowerShell/DscResources/issues/58

### CODE REVIEW

**Comment by olljanat** [comment]
Very nice feature and works fine at least on my lab :)

Hopefully it will be merged to master on some day.

**Comment by briantist** [comment]
Thanks @olljanat , I hope so too!

**Comment by mgreenegit** [comment]
This is very useful.  It has been a common ask to be able to handle publicly trusted certs.  Great set of tests.  I haven't validated it in a lab environment but I see someone has already, so I think we are good to go.

**Comment by briantist** [comment]
@KarolKaczmarek  / @mgreenegit  great news, glad to see it merged. Do you guys have a set schedule or roadmap for the changes in `dev` to make it into `master`? Thanks!

**Comment by KarolKaczmarek** [comment]
the next release is planned in about 3 weeks, until then, feel free to use feed with our development builds: https://github.com/powershell/dscresources/#development-builds

**Comment by KarolKaczmarek** [comment]
Also, thanks a lot for contributing @briantist and sorry it took so long to review and merge this PR!

**Comment by briantist** [comment]
Thank you @KarolKaczmarek ; glad to help. I hope to contribute more in the future.

**Pull request merged**
