### PR TITLE
Requesting certificates using enrollment web services. (Issue  #49)

### PR DESCRIPTION
**Pull request by gammalost**
Added functionality for requesting certificates by using **Enrollment Web Service - CES** and **Enrollment Policy Web Service - CEP** allowing external servers to request certificates. 

* MSFT_xCertReq.psm1
  * Added parameter to specify CA type e.g. **Standalone** or **Enterprise** (defaults to the latter).
  * **Certificate Template** will only be added to the *.inf* file if the default CA type is specified.
  * Added parameters for **CES** and **CEP** URLs.
  * **certreq  -new** and **-submit** can now use Credentials and URLs to CEP and CES (if specified) to request certificates.
* MSFT_xCertReq.schema.mof
  * Added entries for CA type, CES and CEP

Because of the change to creating the **.inf** file mentioned above some tests are failing. I'm quite new to testing so I would appreciate some feedback on how to change the tests to fit the new functionality, also on how to test the new functionality :slightly_smiling_face:

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/56)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @gammalost - great job on submitting this and thank you! It looks like the unit tests are breaking though. Are you able to take a look? I'll review once the tests are working.

**Comment by PlagueHO** [comment]
Oh. And also the merge conflicts :grin:

**Comment by gammalost** [comment]
Hi @PlagueHO! I've tested a bit on why the unit tests fails and have concluded that it is related to the **inf** file generation, but I can't for the life of me understand why they are failing as it should generate the same output.

This is how the removal of the cert template parameter in the **inf** file is done now
**xCertReq.psm1**
```Powershell
# Create INF file
    $requestDetails = @"
[NewRequest]
Subject = $Subject
KeySpec = $keySpec
KeyLength = $KeyLength
Exportable = $($Exportable.ToString().ToUpper())
MachineKeySet = $MachineKeySet
SMIME = $smime
PrivateKeyArchive = $privateKeyArchive
UserProtected = $userProtected
UseExistingKeySet = $useExistingKeySet
ProviderName = $ProviderName
ProviderType = $providerType
RequestType = $requestType
KeyUsage = $KeyUsage
"@
    # If an enterprise CA is used a certificate template must be provided.
    if ($CAType -eq 'Enterprise')
    {
        $requestDetails += @"

[RequestAttributes]
CertificateTemplate = $CertificateTemplate
"@
    }

    $requestDetails += @"
    
[EnhancedKeyUsageExtension]
OID = $OID
"@
```

The here-string used in the unit test should AFAIK be the same as long as nothing else than **enterprise** is sent as a parameter
**xCertReq.Tests.ps1**
```powershell
        $CertInf = @"
[NewRequest]
Subject = "CN=$validSubject"
KeySpec = 1
KeyLength = $KeyLength
Exportable = $($Exportable.ToString().ToUpper())
MachineKeySet = TRUE
SMIME = FALSE
PrivateKeyArchive = FALSE
UserProtected = FALSE
UseExistingKeySet = FALSE
ProviderName = $ProviderName
ProviderType = 12
RequestType = CMC
KeyUsage = $KeyUsage
[RequestAttributes]
CertificateTemplate = $CertificateTemplate
[EnhancedKeyUsageExtension]
OID = $OID
"@
```
I'm fairly new to testing in general so would love some pointers, both to this problem and possibly how to build relevant unit tests for the new functionality :slightly_smiling_face:

**Comment by PlagueHO** [comment]
No problem @gammalost - testing can be one of the trickiest parts of any change. Once the other two outstanding PRs are through I'll take a look at this one as those will cause your one some more merge conflicts. Sorry about taking so long on this!

**Comment by PlagueHO** [comment]
@gammalost - Ok, I had a look at the tests to see why they're failing. The problem is that there is a test (10 to be precise) that checks that the `Set-Content` cmdlet on [this line](https://github.com/PowerShell/xCertificate/blob/dev/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L356) is saving the correct information.

But because you've changed the information that is being saved here, you'll also need to change the tests to reflect this. The test can be found starting on this line:
https://github.com/PowerShell/xCertificate/blob/dev/Tests/Unit/MSFT_xCertReq.Tests.ps1#L291

But, the code you'll actually need to change to make the test pass is here:
https://github.com/PowerShell/xCertificate/blob/dev/Tests/Unit/MSFT_xCertReq.Tests.ps1#L225

You need to make this string match what you'd expect the real code to generate. This may also mean that you'll actually want to adjust the parameters being passed to Set-TargetResource in the test (here: https://github.com/PowerShell/xCertificate/blob/dev/Tests/Unit/MSFT_xCertReq.Tests.ps1#L302) to ensure that the full INF content is being generated. The goal is to ensure we're testing as much of our code as possible.

Does all that make sense?

**Comment by PlagueHO** [comment]
Anyway, once the tests pass, I'll do a proper review on it. I think there is a couple of things in there I've noticed that we might be able to optimize (to reduce shared code or ensure we're not implementing a breaking change - as that requires a whole lot of additional things to be done to release).

**Comment by gammalost** [comment]
It makes sense. What i find peculiar is that the INF content in the test and in the resource should be the same. The new parameter I've added that defaults to **Enterprise** should result in the necessary content regarding certification template to be added in the INF, and should therefore not break the tests(?). 
```powershell
    if ($CAType -eq 'Enterprise')
    {
        $requestDetails += @"

[RequestAttributes]
CertificateTemplate = $CertificateTemplate
"@
    }
```

**Comment by PlagueHO** [comment]
I think what the problem could be is the CRLFs. It looks like you've added some CRLFs between the sections (above the `[RequestAttributes]`) which will cause the string in the unit test to not match. So you can either remove the CRLF from above the sections or add them to the comparison string in the tests.

**Comment by gammalost** [comment]
You sir are correct. Did not even think about that, I kind of shamelessly copied how it was done to the rest of the parameters that were added to the file (newbie errors). I rewrote how it is removed to instead leave the original creation of **$requestDetails** as is, and instead replace portion of the here-string if something other than **enterprise** is passed.
```powershell
    if ($CAType -ne 'Enterprise')
    {
        $requestDetails = $requestDetails.Replace(@"
[RequestAttributes]
CertificateTemplate = $CertificateTemplate
[EnhancedKeyUsageExtension]
"@, '[EnhancedKeyUsageExtension]')
    }
```

Regarding test-scenarios for this code; as it is reliant on credentials and the URL for both CEP and CES would the following scenario make sense?

* CEP and CES URLs passed, credentials not passed

As templates will be removed from the request details when standalone is used i reckon a test for the new request details will be required as well?

**Comment by PlagueHO** [comment]
@gammalost - haha I think I had the exact same trouble when I wrote the tests in the first place - so you're not alone there :grin:

I definitely think it would be beneficial to add tests for these new scenarios. Especially as I'm going to be adding CodeCov.io support soon to this repo (it evaluates our test coverage) - e.g. https://codecov.io/gh/PowerShell/xStorage

So keeping the Unit test coverage high will be good :grin:

**Comment by gammalost** [comment]
@PlagueHO There, I've added tests for web-enrollment to both standalone and enterprise CA. The test towards standalone will also check that the **inf** content do not contain templates. Can you think of any more relevant tests?

**Comment by PlagueHO** [comment]
Thanks for your work on this @gammalost - great job and nearly there! :grin:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[ReadMe.md, line 79 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/56#-KiiOSiYLuZJVneKW65B:-KiiOSiYLuZJVneKW65C:b-fehl7z) ([raw file](https://github.com/powershell/xcertificate/blob/4a2f8b6264b17b3340d7680166081262a3e458cc/ReadMe.md#L79)):*
> ```Markdown
> ### Unreleased
> 
> <<<<<<< HEAD
> ```

Can you remove these conflict markers?

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 61 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/56#-KiiOZFRZ4KgGR1DOfbW:-KiiOZFRZ4KgGR1DOfbX:b7401l) ([raw file](https://github.com/powershell/xcertificate/blob/4a2f8b6264b17b3340d7680166081262a3e458cc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L61)):*
> ```PowerShell
>     .PARAMETER CesURL
>     The URL to the Certification Enrollment Service.
> ```

Can you please remove this blank line?

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 427 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/56#-KiiPyjnOAxJwRBmYASk:-KiiPyjnOAxJwRBmYASl:bt4y7nj) ([raw file](https://github.com/powershell/xcertificate/blob/4a2f8b6264b17b3340d7680166081262a3e458cc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L427)):*
> ```PowerShell
>         ) -join '' )
> 
>     # If enrollment server is specified the request will be towards
> ```

Can you change these two lines to be a comment block? e.g.
<#
  If enrollment server is specified the request will be towards
  the specified URLs instead, using credentials for authentication.
#>
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 442 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/56#-KiiOxdIWn7aG86aIUq9:-KiiOxdJ9Qv9FCulcLiI:b-gz0jiz) ([raw file](https://github.com/powershell/xcertificate/blob/4a2f8b6264b17b3340d7680166081262a3e458cc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L442)):*
> ```PowerShell
>         )
>     }
>     else {
> ```

Can you move the { to the next line?

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 464 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/56#-KiiPXPGOnfm7UZLaYNm:-KiiPXPGOnfm7UZLaYNn:bt4y7nj) ([raw file](https://github.com/powershell/xcertificate/blob/4a2f8b6264b17b3340d7680166081262a3e458cc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L464)):*
> ```PowerShell
>         if ($Credential)
>         {
>             # If enrollment server is specified the request will be towards
> ```

Can you change these two lines to be a comment block? e.g.
<#
  If enrollment server is specified the request will be towards
  the specified URLs instead, using credentials for authentication.
#>
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-comments

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 479 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/56#-KiiP-mO5-_i2X9oOhWQ:-KiiP-mO5-_i2X9oOhWR:b-gz0jiz) ([raw file](https://github.com/powershell/xcertificate/blob/4a2f8b6264b17b3340d7680166081262a3e458cc/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L479)):*
> ```PowerShell
>                 )
>             }
>             else {
> ```

Can you move the { to the next line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/56#-:-KiiQ8gnqLMQBbloI9VU:b-in9fct)*

**Comment by gammalost** [comment]
@PlagueHO No problem :slightly_smiling_face: The necessary corrections have been made, and I've also added the new parameters to xCertReq in the README file.

**Comment by PlagueHO** [comment]
Thanks @gammalost - great job!

:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/56#-:-KiqyBcWbADJ6j5pcRwz:bqgnvtz)*

**Pull request merged**
