### PR TITLE
PR to fix issue 61 for DNS SANs

### PR DESCRIPTION
**Pull request by SeanEGray**
Adds code to Test-TargetResource to check that DNS Names in SANs are correct.
Does not handle other types of SANs, but a similar technique could probably be implemented.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/62)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Really great job and thank you for submitting this fix! Nice stuff.

Just a couple of minor style changes and a possible simplification.

Are you also able to add an entry to the #Unreleased section of the README.MD mentioning the fix?

Also, is it possible to add a unit test to cover this new code path? Happy to help with tests if you need it.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 756 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/62#-Kjyh5nT9Z78J8NvegdV:-Kjyh5nT9Z78J8NvegdW:bemy4et) ([raw file](https://github.com/powershell/xcertificate/blob/39acb5b6acf8638acda04257de34d323edb9102d/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L756)):*
> ```PowerShell
>         if ($PSBoundParameters.ContainsKey('SubjectAltName')) {
>             # Split the desired SANs into an array
>             $SanList = $SubjectAltName.Split('&')
> ```

Local variable name first letter should be lower case (e.g. `$sanList`) - same in following lines

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 780 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/62#-KjyiXjIODU_QR2hrhJ0:-KjyiXjJeRM1mZ5w_m6k:brhcidr) ([raw file](https://github.com/powershell/xcertificate/blob/39acb5b6acf8638acda04257de34d323edb9102d/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L780)):*
> ```PowerShell
>             
>             # Do the cert's DNS SANs and the desired DNS SANs match?
>             if ($CurrentDNSString -ne $CorrectDNSString) {
> ```

There is another possibly simpler way to do this:
```powershell
if (@(Compare-Object -DifferenceObject $CorrectDNS -ReferenceObject $CurrentSANList).Count -gt 0) {
  return $false
}
```

This way you wouldn't need to order or assemble the arrays back into a strings which would reduce the amount of code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/62#-:-KjyiefjZeXZthIlS9Wz:bq9up0l)*

**Comment by SeanEGray** [comment]
Sorry for delay - must've missed your comment. I'll take a look at these suggestions.

**Comment by PlagueHO** [comment]
Hi @SeanEGray -  sorry, I merged another PR and it caused a merge conflict in your PR. Are you able to resolve for me and I'll get the review out this weekend! Sorry about the delays sir!

**Comment by SeanEGray** [comment]
I've implemented the suggestions and resolved the merge conflict.

**Comment by SeanEGray** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 756 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/62#-Kjyh5nT9Z78J8NvegdV:-KkknMpFnduXIHwqfIFv:b-eril5u) ([raw file](https://github.com/powershell/xcertificate/blob/39acb5b6acf8638acda04257de34d323edb9102d/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L756)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Local variable name first letter should be lower case (e.g. `$sanList`) - same in following lines
</blockquote></details>

This change has been made.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 780 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/62#-KjyiXjIODU_QR2hrhJ0:-KkknNIHWHMxCD-W35Ug:b-eril5u) ([raw file](https://github.com/powershell/xcertificate/blob/39acb5b6acf8638acda04257de34d323edb9102d/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L780)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

There is another possibly simpler way to do this:
```powershell
if (@(Compare-Object -DifferenceObject $CorrectDNS -ReferenceObject $CurrentSANList).Count -gt 0) {
  return $false
}
```

This way you wouldn't need to order or assemble the arrays back into a strings which would reduce the amount of code.
</blockquote></details>

This change has been made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/62)*

**Comment by PlagueHO** [comment]
Reviewed 1 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/62)*

**Comment by PlagueHO** [comment]
Thanks again @SeanEGray - great job!

:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/62#-:-KktfGmKdNOSsE8CNooF:b-jxtycb)*

**Pull request merged**
