### PR TITLE
Convert to Auto-documentation/Wiki format - Fixes #84

### LINKED ISSUE #84: Convert to Auto-documentation Format
Convert this resource module over to use the auto-documentation format from SharePointDsc/xNetworking/xStorage/xDFS.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR updates the module to use TestHarness/Auto-documentation/Wiki format created in SharePointDsc (and copied to xNetworking, xStorage and xDFS).

_Autoformatting was applied to a couple of the modules which corrected a few style inconsistencies._

**This Pull Request (PR) fixes the following issues:**
Fixes #84

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@Johlju - if you wouldn't mind reviewing this when you get a chance. I'll do some work at some point on HQRM for this but just wanted to get this out of the way first.

@kwirkykat - would you mind going to settings in this repo and enabling the Wiki for me?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/95)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 83 of 83 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.vscode/launch.json, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/95#-KrKkRta3bJHcDw3B47_:-KrKkRta3bJHcDw3B47a:bfz1lqt) ([raw file](https://github.com/powershell/xcertificate/blob/e1b990c477558a75095097d06aa9984d4c4fefe5/.vscode/launch.json#L1)):*
> ```JSON
> {
> ```

This file shouldn't be here? Good as-is if it was you intent

---

*[.vscode/RunAllTests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/95#-KrKkZg5kkcrlAbQ88WU:-KrKkZg5kkcrlAbQ88WV:b-j4qen9) ([raw file](https://github.com/powershell/xcertificate/blob/e1b990c477558a75095097d06aa9984d4c4fefe5/.vscode/RunAllTests.ps1#L1)):*
> ```PowerShell
> [string] $repoRoot = Split-Path -Path (Split-Path -Path $Script:MyInvocation.MyCommand.Path)
> ```

This neither?  Good as-is if it was you intent

---

*[Modules/xCertificate/DSCResources/MSFT_xPfxImport/en-us/MSFT_xPfxImport.strings.psd1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/95#-KrKlpU8SoOW63xdsmNq:-KrKlpU8SoOW63xdsmNr:b-oa9sy3) ([raw file](https://github.com/powershell/xcertificate/blob/4c4575788935935aa717390cba72e60526b85f71/Modules/xCertificate/DSCResources/MSFT_xPfxImport/en-us/MSFT_xPfxImport.strings.psd1#L1)):*
> ```PowerShell
> ConvertFrom-StringData @'
> ```

Folder is 'en-us'. Change to 'en-US'? Same for all/many string files. You can do that if next PR if it's easier. Good as-is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/95#-:-KrKmaYtMw8L7ZJcWVUe:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks again for reviewing @Johlju!

---

Review status: 49 of 54 files reviewed at latest revision, 3 unresolved discussions.

---

*[.vscode/launch.json, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/95#-KrKkRta3bJHcDw3B47_:-KrKp97yjWKQr7GORo9W:b-z5w8lo) ([raw file](https://github.com/powershell/xcertificate/blob/e1b990c477558a75095097d06aa9984d4c4fefe5/.vscode/launch.json#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This file shouldn't be here? Good as-is if it was you intent
</blockquote></details>

It is intended. We use this file in Harness type repos to easily run all tests from within VSCode. Handy :grin:

---

*[.vscode/RunAllTests.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/95#-KrKkZg5kkcrlAbQ88WU:-KrKpHlNE_Wxda9W7aXh:b-ce3kqt) ([raw file](https://github.com/powershell/xcertificate/blob/e1b990c477558a75095097d06aa9984d4c4fefe5/.vscode/RunAllTests.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This neither?  Good as-is if it was you intent
</blockquote></details>

Same with this one. It runs harness tests.

---

*[Modules/xCertificate/DSCResources/MSFT_xPfxImport/en-US/MSFT_xPfxImport.strings.psd1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/95#-KrKlpU8SoOW63xdsmNq:-KrKpSIN2R19dj7iEDTa:bqe9mcp) ([raw file](https://github.com/powershell/xcertificate/blob/4c4575788935935aa717390cba72e60526b85f71/Modules/xCertificate/DSCResources/MSFT_xPfxImport/en-US/MSFT_xPfxImport.strings.psd1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Folder is 'en-us'. Change to 'en-US'? Same for all/many string files. You can do that if next PR if it's easier. Good as-is.
</blockquote></details>

I corrected all the capitalization... but unfortunately it'll want them to be signed off I think! :cry:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/95#-:-KrKpb_3meh5h2i8db_A:bktr7l8)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 5 of 88 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/95#-:-KrKt-E_dvIWh8Typ7Kl:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @Johlju !

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/95#-:-KrKw6pK5SIOXPsZIN6b:byb9dz7)*

**Pull request merged**
