### PR TITLE
Enable CodeCov.io Support - Fixes #78

### LINKED ISSUE #78: Add CodeCov.io support
I thought I had already enabled this in this module, but it turns out I had forgotten.

### PR DESCRIPTION
**Pull request by PlagueHO**
This adds support for CodeCov.io code coverage analysis.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/79)

### CODE REVIEW

**Comment by PlagueHO** [comment]
One more for you @bgelens - hopefully it is trivial (just adds CodeCov.io support).

**Comment by bgelens** [comment]
:lgtm: I would add dev branch badges (build and codecov) as well (see comment)

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 4 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/79#-KoZ5QxRFjvptWYZs_bM:-KoZ5QxRFjvptWYZs_bN:b-dgsdrw) ([raw file](https://github.com/powershell/xcertificate/blob/616a9935cbce709541f3cf6dfb2d039738d088ad/ReadMe.md#L4)):*
> ```Markdown
> 
> [Build status](https://ci.appveyor.com/project/PowerShell/xcertificate/branch/master)
> [codecov](https://codecov.io/gh/PowerShell/xCertificate)
> ```

I would add build and codecov badges from the dev branch as well. This will give you a better view of improvements being made and actual build status before merging to master

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79#-:-KoZ5toy5rG9vFpwiRdn:b-vcx71f)*

**Comment by PlagueHO** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 4 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/79#-KoZ5QxRFjvptWYZs_bM:-KoZL5XX3MY4wlvy3mwY:b-t8jgis) ([raw file](https://github.com/powershell/xcertificate/blob/616a9935cbce709541f3cf6dfb2d039738d088ad/ReadMe.md#L4)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

I would add build and codecov badges from the dev branch as well. This will give you a better view of improvements being made and actual build status before merging to master
</blockquote></details>

Great idea! Done. Copied the style from PSDscResources.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79)*

**Comment by PlagueHO** [comment]
@bgelens - should be good to go now hopefully!

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79#-:-KoZLAkX0c3rP7Fs_hFw:b-zb638t)*

**Comment by johlju** [comment]
@bgelens is busy with work this week so I stepping in as co-reviewer (plus I have a ton of PR's waiting for him)  :laughing: 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[appveyor.yml, line 24 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/79#-KoqtsU2jv4bajNVVl4q:-KoqtsU2jv4bajNVVl4r:ba6udwe) ([raw file](https://github.com/powershell/xcertificate/blob/cbd1b0e097c1e2f9cf7e51036958fd9c43736980/appveyor.yml#L24)):*
> ```YAML
> test_script:
>     - ps: |
>         Invoke-AppveyorTestScriptTask `
> ```

Need to add `-ExcludeTag @()` to be able to opt-in in the future.

---

*[ReadMe.md, line 7 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/79#-KoqudW5SmFOmNfSDXZS:-KoqudW5SmFOmNfSDXZT:brqg7b1) ([raw file](https://github.com/powershell/xcertificate/blob/cbd1b0e097c1e2f9cf7e51036958fd9c43736980/ReadMe.md#L7)):*
> https://codecov.io/gh/PowerShell/xCertificate

Should point to the dev branch?

https://codecov.io/gh/PowerShell/xCertificate/branch/dev

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79#-:-KoquCbUXKZKmft5Uk2s:b-6208il)*

**Comment by PlagueHO** [comment]
Thanks for doing this @johlju - and thanks for helping @bgelens out ! You're both doing a fantastic job!

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[appveyor.yml, line 24 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/79#-KoqtsU2jv4bajNVVl4q:-KosGiMuhzkVAmm6zWqU:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/cbd1b0e097c1e2f9cf7e51036958fd9c43736980/appveyor.yml#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Need to add `-ExcludeTag @()` to be able to opt-in in the future.
</blockquote></details>

Done.

---

*[ReadMe.md, line 7 at r3](https://reviewable.io:443/reviews/powershell/xcertificate/79#-KoqudW5SmFOmNfSDXZS:-KosGiuHa_YYWOPL3c7f:b-5vwo2w) ([raw file](https://github.com/powershell/xcertificate/blob/cbd1b0e097c1e2f9cf7e51036958fd9c43736980/ReadMe.md#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> https://codecov.io/gh/PowerShell/xCertificate

Should point to the dev branch?

https://codecov.io/gh/PowerShell/xCertificate/branch/dev
</blockquote></details>

Although this is different to PSDscResources, I think you're right. So I've done this too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79#-:-KosHb3sCWNomAvBxN7z:b-ate1jr)*

**Comment by johlju** [comment]
:lgtm:

@PlagueHO You doing a fantastic job as well! 

---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79#-:-Kovi619XJgilLIKZy4w:b-64o0dq)*

**Comment by PlagueHO** [comment]
Hi @Johlju - if you get a chance, could you check this one off for me? I found that I hadn't updated the examples in the README.MD to match so had to tweak them.

**Comment by johlju** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/79#-:-Kpe_eDKaNsS77xRSMYM:bnfp4nl)*

**Pull request merged**
