### PR TITLE
Basic schema validation tests for MSFT_xCertReq

### PR DESCRIPTION
**Pull request by Dan1el42**
Added basic schema validation tests for MSFT_xCertReq. More specific tests coming soon.

### CODE REVIEW

**Comment by Dan1el42** [comment]
Sorry for the hassle. Not sure why GitHub considers the PR as non-mergeable. The AppVeyor build worked on my fork after fixing up the appveyor.yml file - https://ci.appveyor.com/project/Dan1el42/xcertificate/build/1.1.4.0.

**Comment by KarolKaczmarek** [comment]
Thanks for your contribution @Dan1el42 
This PR is marked as non-mergable due to existing conflicts.
Please resolve them and tests should be able to run

```
Step 1: From your project repository, check out a new branch and test the changes.
git checkout -b Dan1el42-basic_schema_validation_tests dev
git pull https://github.com/Dan1el42/xCertificate.git basic_schema_validation_tests

Step 2: Merge the changes and update on GitHub.
git checkout dev
git merge --no-ff Dan1el42-basic_schema_validation_tests
git push origin dev
```

**Comment by Dan1el42** [comment]
PR obsolete once the basic schema validation tests are merged for DscResource,Tests.

**Comment by Dan1el42** [comment]
@KarolKaczmarek, Thanks very much for the instructions.

**Pull request closed without merging**
