### PR TITLE
$configContext.ToString()

### PR DESCRIPTION
**Pull request by amrowicki**
$configContext.ToString() for returning System.String instead of System.DirectoryServices.PropertyValueCollection

**Pull Request (PR) description**

$cdpContainer = [ADSI]('LDAP://CN=CDP,CN=Public Key Services,CN=Services,{0}' -f $configContext) returns an error:
format-default : The following exception occurred while retrieving member "distinguishedName": "An invalid dn syntax has been specified.
"
    + CategoryInfo          : NotSpecified: (:) [format-default], ExtendedTypeSystemException
    + FullyQualifiedErrorId : CatchFromBaseGetMember,Microsoft.PowerShell.Commands.FormatDefaultCommand

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/92)

### CODE REVIEW

**Comment by PlagueHO** [comment]
A great catch there @amrowicki ! And thank you for submitting the fix!

Are you able to add an entry to the README.MD file `Unrleased` section mentioning this fix? https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#fixing-an-issue

 E.g. to this part of the file:
https://github.com/PowerShell/xCertificate/blob/dev/ReadMe.md#unreleased

Thank you

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/92#-:-KrACq1HN5WqFI41cBIJ:b-qbt4w3)*

**Comment by amrowicki** [comment]
The entry has been added. Thanks!

**Comment by kwirkykat** [comment]
@amrowicki @PlagueHO Please make sure you are merging into dev instead of master next time

**Comment by PlagueHO** [comment]
Sorry abouth that @KwirkyKat ! I completely missed that. Will keep an eye on it. Thanks for picking this up.

**Pull request merged**
