### PR TITLE
Prevent ResourceHelper and Common cmdlets from being exported - Fixes #64

### LINKED ISSUE #64: Breaking change: Get-LocalizedData command
```
PS C:\Users\GlennMate> Install-Module xNetworking -Force
PackageManagement\Install-Package : A command with name 'Get-LocalizedData' is already available on this system. This
module 'xNetworking' may override the existing commands. If you still want to install this module 'xNetworking', use
-AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage
```

As of the 4.0.0.0 release today, this module now conflicts with the newly released 3.0.0.0 version of xStorage. The only way to install this module is to use `Install-Module xNetworking -Force -AllowClobber`. This should break aliases between DSC resources. 

Please address ASAP, this is a big breaking change. 

This issue was raised by @glennmate in xNetworking here: https://github.com/PowerShell/xNetworking/issues/213

### PR DESCRIPTION
**Pull request by PlagueHO**
This resolves a high priority issue with newer versions of xNetworking, xCertificate, xStorage and xDFS conflicting with each other because the ResourceHelper cmdlets are being exported due to the way each resource imported them (using the PSD1 nested modules array).

This should be resolved in xNetworking, xStorage and xDFS as well to ensure no other conflicts.

This also contains a new integration test that will check for any further conflicts between resource modules. At some point it might be possible to move this test into the DSCResource.Tests common tests to provide more comprehensive conflict prevention. However, because the conflicts will potentially be between three different modules the number of modules compared will have to go in over time.

This fixes #64

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/65)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[ReadMe.md, line 75 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZQPYzfsu4m5vg0VgG:-KlZQPYzfsu4m5vg0VgH:bgytttn) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/ReadMe.md#L75)):*
> ```Markdown
> - **`[Boolean]` IsExported** (_Read_): Returns true if the certificate file already exists and therefore has been exported.
> 
> ## Versions
> ```

version here seem out of place.

---

*[ReadMe.md, line 77 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZQTB-yyQMyKuhYIN4:-KlZQTB-yyQMyKuhYIN5:bt02ie4) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/ReadMe.md#L77)):*
> ```Markdown
> ## Versions
> 
> - Added integration test to test for conflicts with other common resource kit modules.
> ```

This is also under Unreleased. Should not be here?

---

*[DSCResources/MSFT_xCertificateExport/MSFT_xCertificateExport.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZR2UlOGIpfiDXQkFk:-KlZR2UmewppW_foOKVa:bpiplgz) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/DSCResources/MSFT_xCertificateExport/MSFT_xCertificateExport.psm1#L14)):*
> ```PowerShell
>                                -ChildPath (Join-Path -Path 'CertificateDsc.ResourceHelper' `
>                                                      -ChildPath 'CertificateDsc.ResourceHelper.psm1'))
> ```

Just want to make sure. CertificateDsc.PDT.psm1 is not needed in this resource?

---

*[DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZRFtnfVeqDyshBt5F:-KlZRFtnfVeqDyshBt5G:bpiplgz) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1#L14)):*
> ```PowerShell
>                                -ChildPath (Join-Path -Path 'CertificateDsc.ResourceHelper' `
>                                                      -ChildPath 'CertificateDsc.ResourceHelper.psm1'))
> ```

Just want to make sure. CertificateDsc.PDT.psm1 is not needed in this resource?

---

*[DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZRTnYMxVr1lbsMHdQ:-KlZRTnYMxVr1lbsMHdR:bpiplgz) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1#L14)):*
> ```PowerShell
>                                -ChildPath (Join-Path -Path 'CertificateDsc.ResourceHelper' `
>                                                      -ChildPath 'CertificateDsc.ResourceHelper.psm1'))
> ```

Just want to make sure. CertificateDsc.PDT.psm1 is not needed in this resource?

---

*[Tests/Integration/ModuleConflict.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZQv5SfRT2E8xdzem6:-KlZQv5SfRT2E8xdzem7:bowa8fa) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/Tests/Integration/ModuleConflict.Tests.ps1#L37)):*
> ```PowerShell
>                 {
>                     Install-Module -Name $moduleToTest -ErrorAction Stop
>                 } | Should not throw
> ```

Same comment as in xStorage

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/65)*

**Comment by PlagueHO** [comment]
All done! Again thank you so much @johlju!

---

Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[ReadMe.md, line 75 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZQPYzfsu4m5vg0VgG:-Kl_Hc1Mun4B3KJNSdYy:b-5mxya7) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/ReadMe.md#L75)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

version here seem out of place.
</blockquote></details>

Doh! Fixed.

---

*[ReadMe.md, line 77 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZQTB-yyQMyKuhYIN4:-Kl_HdvICc20dUSk-E0D:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/ReadMe.md#L77)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This is also under Unreleased. Should not be here?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xCertificateExport/MSFT_xCertificateExport.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZR2UlOGIpfiDXQkFk:-Kl_HexgVeBFIUkgvtTv:b-555c76) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/DSCResources/MSFT_xCertificateExport/MSFT_xCertificateExport.psm1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Just want to make sure. CertificateDsc.PDT.psm1 is not needed in this resource?
</blockquote></details>

That is correct. xPDT only required in xCertReq. But that is definitely good thinking.

---

*[DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZRFtnfVeqDyshBt5F:-Kl_HjWvXysbxwTrPhzB:b-555c76) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Just want to make sure. CertificateDsc.PDT.psm1 is not needed in this resource?
</blockquote></details>

That is correct. xPDT only required in xCertReq. But that is definitely good thinking.

---

*[DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, line 14 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZRTnYMxVr1lbsMHdQ:-Kl_Hk9wQGJ27rZx-jhJ:b-555c76) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Just want to make sure. CertificateDsc.PDT.psm1 is not needed in this resource?
</blockquote></details>

That is correct. xPDT only required in xCertReq. But that is definitely good thinking.

---

*[Tests/Integration/ModuleConflict.Tests.ps1, line 37 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/65#-KlZQv5SfRT2E8xdzem6:-Kl_I56U8Lyg99wD3nRU:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/3110a6f9cdd2d7ea6fc3389892e87145d8af3fba/Tests/Integration/ModuleConflict.Tests.ps1#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same comment as in xStorage
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/65#-:-Kl_I7D-iCxkNDlNsOga:bltr9i0)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/65#-:-Kl_Iby_ANR-icbMIWzz:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @johlju !

**Pull request merged**
