### PR TITLE
Adds new xCertreq parameters - Fixes #25

### LINKED ISSUE #25: [New Feature] Extend xCertReq to Support additional Parameters
At the company I work for we're going to be needing some additional features in this resource:
1. TemplateName - the name of the CA template to use.
2. KeyLength - the request is set to 1024 - should be defineable.
3. Exportable - Defaults to True, but this should be definable.
4. ProviderName - Should allow selection - KSP is recommended when using SHA-2. CSP is currently only option.
5. OID - should be able to override this.
6. KeyUsage - should be able to override this.

Would there be any objections to us adding these features and submitting them to this resource over the next few weeks?

### PR DESCRIPTION
**Pull request by SteelCrusaders**
Added additional parameters to xCertReq - 
(KeyLength, Exportable, ProviderName, OID, KeyUsage, CertificateTemplate)

Dependent on PR #29 as issued by @PlagueHO.

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/30)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Sorry @SteelCrusaders - I had to do some more work on my PR ( #29 ) based on the feedback from @kwirkykat. So you'll need to rework this PR a bit too. Shouldn't be too much but I'll take you through the differences on Monday.

**Comment by PlagueHO** [comment]
We'll resolve the merge conflicts on this PR over the next day or so.

**Comment by PlagueHO** [comment]
This PR can be reviewed now. Sorry about the delay.

**Comment by mgreenegit** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by kwirkykat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KVaMDg6sV-fRUqQIZNf:-KVaMDg6sV-fRUqQIZNg:b-2jqhp1) ([raw file](https://github.com/powershell/xcertificate/blob/ebd9fed32b05aaca032955596f41d394300e9076/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L87)):*
> [parameter(Mandatory = $false)]

All of these should be `[Parameter()]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by PlagueHO** [comment]
@KwirkyKat - I also fixed most of the Markdown violations in the Readme.md.

---

Reviewed 2 of 4 files at r2.
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KVaMDg6sV-fRUqQIZNf:-KVcj2Ycb770dfO3XpkB:b-ve3o84) ([raw file](https://github.com/powershell/xcertificate/blob/ebd9fed32b05aaca032955596f41d394300e9076/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L87)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > [parameter(Mandatory = $false)]
> 
> All of these should be `[Parameter()]`
</details>
Done - as well as corrected the other PSM1 files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30#-:-KVcj83ibB_BdnXtn5Vn:b9wyh2i)*

**Comment by mgreenegit** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[ReadMe.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KW8u40VT_Koj7_GZKvb:-KW8u40VT_Koj7_GZKvc:bncdln) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/ReadMe.md#L7)):*
> ```Markdown
> The **xCertificate** module is a part of the Windows PowerShell Desired State Configuration (DSC) Resource Kit, which is a collection of DSC Resources. This module includes DSC resources that simplify administration of certificates on a Windows Server, with simple declarative language.
> 
> The **xCertificate** module contains the following resources:
> ```

Would you be willing to take this opportunity to update the resources list in the readme following the new template?
https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/README.md

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by mgreenegit** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ReadMe.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KW8u40VT_Koj7_GZKvb:-KWCPO1OGaW1KlPjtwuV:b-w2m5jr) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/ReadMe.md#L7)):*
<details><summary><i>Previously, mgreenegit (Michael Greene) wrote…</i></summary>
> Would you be willing to take this opportunity to update the resources list in the readme following the new template?
> https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/README.md
</details>
@mgreenegit - absolutely! I'll get this done. However, I noticed a few MD best practice violations on the DSCResources.Template\Readme.md, so I'll get these resolved in the template first. I have raised an issue and will get a decision from the DSC team as to whether or not to support MD best practices. Thanks for pointing this out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ReadMe.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KW8u40VT_Koj7_GZKvb:-KWKrZGm8uEJUcAhQa0I:b-8zaxlm) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/ReadMe.md#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> @mgreenegit - absolutely! I'll get this done. However, I noticed a few MD best practice violations on the DSCResources.Template\Readme.md, so I'll get these resolved in the template first. I have raised an issue and will get a decision from the DSC team as to whether or not to support MD best practices. Thanks for pointing this out.
</details>
@mgreenegit - Ok. It should all match the template now (well, the new one I've submitted as a PR to the DSCResources repo to fix the MD issues). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by kwirkykat** [comment]
@mgreenegit Are you good with this one?

---

Reviewed 7 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KVaMDg6sV-fRUqQIZNf:-KWoWKZB0gS3_rKiOcBP:bu12psu) ([raw file](https://github.com/powershell/xcertificate/blob/ebd9fed32b05aaca032955596f41d394300e9076/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L87)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Done - as well as corrected the other PSM1 files.
</details>
Not a blocker, but they should all be `[Parameter()]` (capital P)

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 432 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoYlKX1pnUGDfuaava:-KWoYlKX1pnUGDfuaavb:b-gr6poc) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L432)):*
> does not throw

Please start all It statement names with 'Should'
(ex: Should return true when Ensure set to Present)

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 435 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoYxoreA6HJCC2Z96x:-KWoYxosG8IKdVDoiu-9:bptbhca) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L435)):*
> calls expected mocks

Please start all It statement names with 'Should'
(ex: Should return true when Ensure set to Present)

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 580 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoYznkMY6HX3c0y3r9:-KWoYznkMY6HX3c0y3rA:b-gr6poc) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L580)):*
> does not throw

Please start all It statement names with 'Should'
(ex: Should return true when Ensure set to Present)

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 584 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoZ0Jb2zcexiOhOPc-:-KWoZ0Jb2zcexiOhOPc0:bptbhca) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L584)):*
> calls expected mocks

Please start all It statement names with 'Should'
(ex: Should return true when Ensure set to Present)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30#-:-KWo_8CsoNpJSz4lHIN9:bapownp)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, line 87 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KVaMDg6sV-fRUqQIZNf:-KWqAUOOivjpMkPVzN7f:b-nkh52h) ([raw file](https://github.com/powershell/xcertificate/blob/ebd9fed32b05aaca032955596f41d394300e9076/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1#L87)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Not a blocker, but they should all be `[Parameter()]` (capital P)
</details>
Fixed this too (I like to get things right). Good catch!

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 432 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoYlKX1pnUGDfuaava:-KWqAGwa0pHy09gAW93J:byw0ijw) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L432)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > does not throw
> 
> Please start all It statement names with 'Should'
> (ex: Should return true when Ensure set to Present)
</details>
Good catch. Fixed (and all the others).

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 435 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoYxoreA6HJCC2Z96x:-KWqANdZp-n4WepGeVWh:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L435)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > calls expected mocks
> 
> Please start all It statement names with 'Should'
> (ex: Should return true when Ensure set to Present)
</details>
Done.

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 580 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoYznkMY6HX3c0y3r9:-KWqAQWE0CeIOGTOjkC2:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L580)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > does not throw
> 
> Please start all It statement names with 'Should'
> (ex: Should return true when Ensure set to Present)
</details>
Done.

---

*[Tests/Unit/MSFT_xCertReq.tests.ps1, line 584 at r2](https://reviewable.io:443/reviews/powershell/xcertificate/30#-KWoZ0Jb2zcexiOhOPc-:-KWqASU0t084oSMg9SLE:b-896fix) ([raw file](https://github.com/powershell/xcertificate/blob/8067debc99419f6cead52f9a32bdf41105dac43f/Tests/Unit/MSFT_xCertReq.tests.ps1#L584)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > calls expected mocks
> 
> Please start all It statement names with 'Should'
> (ex: Should return true when Ensure set to Present)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30)*

**Comment by kwirkykat** [comment]
:lgtm: Just rebase onto dev and the tests should fix themselves.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/30#-:-KWtrKJ2hI11pWoKDSF8:bmnan41)*

**Comment by PlagueHO** [comment]
@kwirkykat - should be good to go now.

**Pull request merged**
