### PR TITLE
Added Documentation and Examples section to README.MD - Fixes #98

### LINKED ISSUE #98: Link Readme.md to Wiki Entries
**Details of the scenario you tried and the problem that is occurring:**
It is not obvious from the README.MD that there is a Wiki containing the full documentation.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Added Documentation and Examples section to README.MD. Wording mostly copied from SharePointDsc.

**This Pull Request (PR) fixes the following issues:**
Fixes #98 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcertificate/99)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - would you mind reviewing this one if you get a moment?

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 29 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/99#-KsTzQPNhiwFVh1AevSy:-KsTzQPNhiwFVh1AevSz:b-otn0ft) ([raw file](https://github.com/powershell/xcertificate/blob/9d86ec8a516c259feed4ea6bae0c6f8e7b7ba9df/ReadMe.md#L29)):*
> en-US

Can't find the folder. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/99)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 29 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/99#-KsTzQPNhiwFVh1AevSy:-KsVN1oGevFV2MSE1_d3:bvwaka8) ([raw file](https://github.com/powershell/xcertificate/blob/9d86ec8a516c259feed4ea6bae0c6f8e7b7ba9df/ReadMe.md#L29)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> en-US

Can't find the folder. :)
</blockquote></details>

That is correct 😁 This folder gets created by the Autodocumenation code - so only exists in modules installed from the PS Gallery. I've changed the wording to better reflect this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/99)*

**Comment by johlju** [comment]
:lgtm:

Please see comment in your PR in xStorage.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ReadMe.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/99#-KsYlDVQejCKuCh_nfwb:-KsYlDVQejCKuCh_nfwc:b-m8i19c) ([raw file](https://github.com/powershell/xcertificate/blob/9d86ec8a516c259feed4ea6bae0c6f8e7b7ba9df/ReadMe.md#L1)):*
> ```Markdown
> # xCertificate
> ```

Extremely minor. the file is 'ReadMe.md', should be 'README.md'? Non-blocking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/99#-:-KsYlNEf6nz8x2vVQrht:b4gee3t)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/xcertificate/99#-KsYlDVQejCKuCh_nfwb:-Ksm6JDWR0OKmp8RFm9X:by5vpz2) ([raw file](https://github.com/powershell/xcertificate/blob/9d86ec8a516c259feed4ea6bae0c6f8e7b7ba9df/README.md#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Extremely minor. the file is 'ReadMe.md', should be 'README.md'? Non-blocking.
</blockquote></details>

Fixed! :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/99)*

**Comment by PlagueHO** [comment]
I've removed this whole paragraph until I can implement a process to ensure this info is all being copied into the Resource Module during release.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/99#-:-Ksm6S0YC44HqZcoI4iy:b-4n6zeb)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xcertificate/99#-:-KsnCrpAKH_CAzjRMHJP:bnfp4nl)*

**Pull request merged**
